database:
    driver: pdo_mysql
    dbname: OCTOPUSH
    host: localhost
    user: root
    password: admin
    port: 3306
jenkins:
    host: localhost:8080
    user: 
    pass: 
    jobs: 
        prefix: 'Push_Artifactory_'
        liveprefix: 'Push_'
        notifications: 'Octopush_Notification'
modules:
    ok-project: 1
    fail-project: 1
    frontend-br: 1
    frontend-in: 1
    fp: 2
    smaug: 2
    abl: 3
    yerba: 1
    dummy_octopush: 1
jobs:
    queue.lenght: 25      #amount of jobs listed in the queue
    processed.lenght: 5   #amount of jobs listed as processed
    priority: queue_date  #priority column 
    waiting.seconds: 10   #seconds between each call to jenkins
log.level: DEBUG          #could be DEBUG, INFO, ERROR
log.path: /var/log/octopush.log
github_key: 'your_key'
github_secret: 'your_secret'
github_management_key: 'your_management_key'
admin_team_id: 'your_admin_team_id'
